name: Run tests
on: [push, pull_request]
permissions: {}
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        distribution: ['zulu']
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [ 17, 21, 22, 23 ]
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
          persist-credentials: false
      - uses: actions/setup-java@v5
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.version }}
      - run: mvn test -B
      # This is after the test run to work around
      # https://issues.apache.org/jira/projects/MJAVADOC/issues/MJAVADOC-736
      - run: mvn javadoc:javadoc
